# Generated by Django 4.1.5 on 2023-01-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_User_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('task_description', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not_Yet_Started', 'Not_Yet_Started'), ('Started', 'Started'), ('Interrupted', 'Interrupted'), ('Completed', 'Completed')], max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completed_task', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.main_user_info')),
            ],
        ),
    ]
