# Generated by Django 4.1.5 on 2023-01-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userinfo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='date_assigned',
            field=models.DateField(),
        ),
    ]
