# Generated by Django 4.1.5 on 2023-03-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_groupinfo_groupsmembers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinfo',
            name='role',
        ),
    ]
