# Generated by Django 4.1.5 on 2023-03-24 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_userinfo_date_assigned"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.groupinfo",
            ),
        ),
    ]
