# Generated by Django 4.1.5 on 2023-01-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=30, null=True)),
                ("date_assigned", models.DateField(auto_now_add=True)),
                ("task_description", models.TextField()),
                ("comments", models.TextField(blank=True, null=True)),
                ("target_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not_Yet_Started", "Not_Yet_Started"),
                            ("Started", "Started"),
                            ("Interrupted", "Interrupted"),
                            ("Completed", "Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("completed_task", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
