# Generated by Django 4.1.5 on 2023-01-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userinfo_date_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('High', 'High'), ('Medium', 'Medium')], max_length=20, null=True),
        ),
    ]
