# Generated by Django 4.1.5 on 2023-03-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_groupinfo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
