# Generated by Django 4.1.5 on 2023-03-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_groupinfo_group_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='date_assigned',
            field=models.DateField(),
        ),
    ]
